# @format

name: Build`
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Insert access keys
        run: chmod +x ./.github/scripts/build.sh && ./.github/scripts/build.sh
        shell: bash

      # https://github.com/docker/build-push-action
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            aeissa/etl-agent:${{ github.sha }}
            aeissa/etl-agent:latest
