# @format

name: S3 Deploy

on: [push]
env:
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  S3_REGION: ${{ vars.S3_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup .env
        run: chmod +x ./.github/scripts/setup-env.sh && ./.github/scripts/setup-env.sh

      - name: Deploy
        run: chmod +x ./.github/scripts/s3-deploy.sh && ./.github/scripts/s3-deploy.sh
